from werkzeug.security import generate_password_hash
from app.models import db, Movie


def seed_movies():

    demo = Movie( movie_name="Mortal Kombat", actors="Lewis Tan Jessica McNamee Josh Lawson Tadanobu Asano Mehcad Brooks"
                                                    , movie_date='April 16, 2021',
                                                    movie_info='Mortal Kombat is an upcoming American martial arts fantasy action film directed by Simon McQuoid (in his feature directorial debut) from a screenplay by Greg Russo and Dave Callaham',
                                                    movie_url='https://www.youtube.com/watch?v=Z5CWOcrw-h8',category_id=1)
    movie7 = Movie( movie_name="Avatar", actors="Sam Worthington, Zoe Saldana, Sigourney Weaver",movie_date='18 December 2009',movie_info='A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',movie_url='https://www.youtube.com/watch?v=_V1lLSS9lCc',category_id=1)
    movie8 = Movie(movie_name='THE VIRTUOSO', actors='Anthony Hopkins, Abbie Cornish, Anson Mount', movie_date='updated in 13 December 2020',movie_info='A lonesome stranger, secure, nerves of steel, must track down and kill a rogue Hitman to satisfy an outstanding debt.',movie_url='https://www.youtube.com/watch?v=7JCK1AUZL1w',category_id=1)
    movie9 = Movie(movie_name='Tom Clancy\'s Without Remorse', actors='Michael B. Jordan, Jodie Turner-Smith, Jamie Bell', movie_date='April 30, 2021',movie_info='John Clark, a Navy SEAL, goes on a path to avenge his wife\'s murder only to find himself inside of a larger conspiracy.',movie_url='https://www.youtube.com/watch?v=mtGjZp3MWrI',category_id=1)
    movie10 = Movie(movie_name='Fast & Furious Presents: Hobbs & Shaw', actors='Dwayne Johnson, Jason Statham, Idris Elba', movie_date='2 August 2019',movie_info='Lawman Luke Hobbs (Dwayne "The Rock" Johnson) and outcast Deckard Shaw (Jason Statham) form an unlikely alliance when a cyber-genetically enhanced villain threatens the future of humanity.',movie_url='https://www.youtube.com/watch?v=HZ7PAyCDwEg',category_id=1)
    movie5 = Movie( movie_name="The Night House", actors="Rebecca Hall, Stacy Martin, Sarah Goldberg",movie_date='16 July 2021',movie_info='A widow begins to uncover her recently deceased husband\'s disturbing secrets.',movie_url='https://www.youtube.com/watch?v=tRsoFy-UwyQ',category_id=2)
    movie6 = Movie( movie_name="Separation", actors="Rupert Friend, Brian Cox, Madeline Brewer",movie_date='April 30, 2021',movie_info='A young girl finds solace in her artist father and the ghost of her dead mother.',movie_url='https://www.youtube.com/watch?v=XJ0fzKnXVCA',category_id=2)
    movie11 = Movie(movie_name='Us', actors=' Lupita Nyong\'o, Winston Duke, Elisabeth Moss', movie_date='22 March 2019',movie_info='A family\'s serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.',movie_url='https://www.youtube.com/watch?v=hNCmb-4oXJA',category_id=2)
    movie12 = Movie(movie_name='Alone', actors='Jules Willcox, Marc Menchaca, Anthony Heald', movie_date='18 September 2020',movie_info='A recently widowed traveler is kidnapped by a cold blooded killer, only to escape into the wilderness where she is forced to battle against the elements as her pursuer closes in on her.',movie_url='https://www.youtube.com/watch?v=RQNL2x4wK1s',category_id=2)
    movie13 = Movie(movie_name='The Seventh Day', actors='Guy Pearce, Vadhir Derbez, Stephen Lang', movie_date='26 March 2021',movie_info='A renowned exorcist who teams up with a rookie priest for his first day of training. As they plunge deeper into hell on earth, the lines between good and evil blur, and their own demons emerge.',movie_url='https://www.youtube.com/watch?v=PpjZ-7OVBQg',category_id=2)
    movie3 = Movie( movie_name="Things Things", actors="Patti Harrison, Ed Helms, Rosalind Chao",movie_date='11 May 2021',movie_info='When a young loner becomes the gestational surrogate for a single man in his 40s, the two strangers come to realize this unexpected relationship will challenge their perceptions of connection, boundaries and the particulars of love.',movie_url='https://www.youtube.com/watch?v=27Sc2YxuQds',category_id=3)
    movie14 = Movie(movie_name='Let\'s Be Cops', actors='Jake Johnson, Damon Wayans Jr., Rob Riggle', movie_date='13 August 2014',movie_info='Two struggling pals dress as police officers for a costume party and become neighborhood sensations. But when these newly-minted "heroes" get tangled in a real life web of mobsters and dirty detectives, they must put their fake badges on the line.',movie_url='https://www.youtube.com/watch?v=tOc5MD50BzQ',category_id=3)
    movie15 = Movie(movie_name='Central Intelligence', actors='Dwayne Johnson, Kevin Hart, Danielle Nicolet', movie_date='17 June 2016',movie_info='After he reconnects with an awkward pal from high school through Facebook, a mild-mannered accountant is lured into the world of international espionage.',movie_url='https://www.youtube.com/watch?v=iUMZviyljUI',category_id=3)
    movie16 = Movie(movie_name='Tom And Jerry', actors='Chloë Grace Moretz, Michael Peña, Colin Jost', movie_date='26 February 2021',movie_info='A chaotic battle ensues between Jerry Mouse, who has taken refuge in the Royal Gate Hotel, and Tom Cat, who is hired to drive him away before the day of a big wedding arrives.',movie_url='https://www.youtube.com/watch?v=fgqEyC19538',category_id=3)
    movie17 = Movie(movie_name='Borat Subsequent', actors='Sacha Baron Cohen, Maria Bakalova, Tom Hanks', movie_date='23 October 2020',movie_info='Borat returns from Kazakhstan to America and this time he reveals more about the American culture, the COVID-19 pandemic and the political elections.',movie_url='https://www.youtube.com/watch?v=JvPTCvUnNQA',category_id=3)
    movie18 = Movie(movie_name='The Mitchells vs. the Machines', actors='Olivia Colman, Eric André, Maya Rudolph', movie_date='April 30, 2021',movie_info='A quirky, dysfunctional family\'s road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity\'s unlikeliest last hope.',movie_url='https://www.youtube.com/watch?v=XviqhAB5sEc',category_id=4)
    movie19 = Movie(movie_name='Luca', actors='Jacob Tremblay, Jack Dylan Grazer, Maya Rudolph', movie_date='June 18, 2021',movie_info='On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.',movie_url='https://www.youtube.com/watch?v=0hgHY9k-44U',category_id=4)
    movie20 = Movie(movie_name='The Boss Baby: Family Business', actors='James Marsden, Jeff Goldblum, Alec Baldwin', movie_date='September 17, 2021',movie_info='The Templeton brothers have become adults and drifted away from each other, but a new boss baby with a cutting-edge approach is about to bring them together again - and inspire a new family business.',movie_url='https://www.youtube.com/watch?v=EWizz52lZvw',category_id=4)
    movie21 = Movie(movie_name='Inside Out', actors='Amy Poehler, Bill Hader, Lewis Black', movie_date='19 June 2015',movie_info='After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.',movie_url='https://www.youtube.com/watch?v=1HFv47QHWJU',category_id=4)
    movie22 = Movie(movie_name='Minions: The Rise of Gru', actors='Danny Trejo, Steve Carell, Lucy Lawless', movie_date='July 1, 2022',movie_info='The untold story of one twelve-year-old\'s dream to become the world\'s greatest supervillain.',movie_url='https://www.youtube.com/watch?v=54yAKyNkK7w',category_id=4)
    movie26 = Movie(movie_name='Psych', actors='James Roday Rodriguez, Dulé Hill, Timothy Omundson', movie_date='TV Series (2006–2014)',movie_info='A novice sleuth is hired by the Police after he cons them into thinking he has psychic powers which help solve crimes. With the assistance of his reluctant best friend, the duo take on a series of complicated cases.',movie_url='https://www.youtube.com/watch?v=HsItWo7eF5s',category_id=5)
    movie27 = Movie(movie_name='Loki', actors='Tom Hiddleston, Owen Wilson, Sophia Di Martino', movie_date=' TV Series (2021– )',movie_info='A new Marvel chapter with Loki at its center.',movie_url='https://www.youtube.com/watch?v=UlnufxrJlAk',category_id=5)
    movie28 = Movie(movie_name='The Falcon and the Winter Soldier', actors='Anthony Mackie, Sebastian Stan, Wyatt Russell', movie_date=' TV Mini-Series (2021)',movie_info='Following the events of \'Avengers: Endgame,\' Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up in a global adventure that tests their abilities -- and their patience.',movie_url='https://www.youtube.com/watch?v=IWBsDaFWyTE',category_id=5)
    movie29 = Movie(movie_name='WandaVision', actors='Elizabeth Olsen, Paul Bettany, Kathryn Hahn', movie_date='15 January 2021',movie_info='Blends the style of classic sitcoms with the MCU, in which Wanda Maximoff and Vision - two super-powered beings living their ideal suburban lives - begin to suspect that everything is not as it seems.',movie_url='https://www.youtube.com/watch?v=3JSEKkbhG4o',category_id=5)
    movie30 = Movie(movie_name='Grace', actors='John Simm, Richie Campbell, William Andrews', movie_date=' TV Mini-Series (2021– )',movie_info='Brighton-based Detective Superintendent Roy Grace, a hard-working police officer who has given his life to the job.',movie_url='https://www.youtube.com/watch?v=6tBO1n6-Km4',category_id=5)
    movie1 = Movie( movie_name="Cherry", actors=" Tom Holland, Ciara Bravo, Jack Reynor",movie_date='March 12 2021',movie_info='Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he struggles to find his place in the world.',movie_url='https://www.youtube.com/watch?v=Nt_wyydppg8',category_id=6)
    movie2 = Movie( movie_name="The Little Things ", actors=" Denzel Washington, Rami Malek, Jared Leto",movie_date=' 29 January 2021',movie_info='Kern County Deputy Sheriff Joe Deacon is sent to Los Angeles for what should have been a quick evidence-gathering assignment. Instead, he becomes embroiled in the search for a serial killer who is terrorizing the city.',movie_url='https://www.youtube.com/watch?v=QXpxUeL0lz4',category_id=6)
    movie23 = Movie(movie_name='Stowaway', actors=' Anna Kendrick, Daniel Dae Kim, Toni Collette', movie_date='April 22, 2021',movie_info='A stowaway on a mission to Mars sets off a series of unintended consequences.',movie_url='https://www.youtube.com/watch?v=nOggbGeuicQ',category_id=6)
    movie24 = Movie(movie_name='Monster Hunter', actors='Milla Jovovich, Tony Jaa, Ron Perlman', movie_date='18 December 2020',movie_info='When Lt. Artemis and her loyal soldiers are transported to a new world, they engage in a desperate battle for survival against enormous enemies with incredible powers. Feature film based on the video game by Capcom.',movie_url='https://www.youtube.com/watch?v=3od-kQMTZ9M',category_id=6)
    movie25 = Movie(movie_name='The Blackout', actors='Aleksey Chadov, Pyotr Fyodorov, Svetlana Ivanova', movie_date='21 November 2019',movie_info='Life on Earth is rapidly destroyed except for a small area in Eastern Europe.',movie_url='https://www.youtube.com/watch?v=DCAixCfVtfE',category_id=6)
    db.session.add(demo)
    db.session.add(movie7)
    db.session.add(movie8)
    db.session.add(movie9)
    db.session.add(movie10)
    db.session.add(movie5)
    db.session.add(movie6)
    db.session.add(movie11)
    db.session.add(movie12)
    db.session.add(movie13)
    db.session.add(movie3)
    db.session.add(movie14)
    db.session.add(movie15)
    db.session.add(movie16)
    db.session.add(movie17)
    db.session.add(movie18)
    db.session.add(movie19)
    db.session.add(movie20)
    db.session.add(movie21)
    db.session.add(movie22)
    db.session.add(movie26)
    db.session.add(movie27)
    db.session.add(movie28)
    db.session.add(movie29)
    db.session.add(movie30)
    db.session.add(movie1)
    db.session.add(movie2)
    db.session.add(movie23)
    db.session.add(movie24)
    db.session.add(movie25)

    db.session.commit()


def undo_movies():
    db.session.execute('TRUNCATE movies;')
    db.session.commit()
# Adds a demo user, you can add other users here if you want
